name: $(date:yyyyMMdd)$(rev:.r)
variables:
  ImageName: 'goginbasic'
jobs:
  - job: BuildJobCI
    displayName: goginbasicCI
    pool:
        name: cia-agent-pool
    steps:
      - checkout: self
      - task: GoTool@0
        displayName: Use Go 1.17.6
        inputs:
          version: 1.17.6
      - task: Go@0
        displayName: go get
        inputs:
          arguments: -d
      - task: Go@0
        displayName: go test
        enabled: False
        inputs:
          command: test
      - task: Go@0
        displayName: go build
        enabled: False
        inputs:
          command: build
          arguments: -o "$(Build.Repository.Name).exe"
      - task: DockerInstaller@0
        displayName: Install Docker 17.09.0-ce
      - task: Docker@2
        displayName: build
        inputs:
          repository: '$(ImageName)'
          command: build
          Dockerfile: Dockerfile
          tags: $(Build.BuildId)
      - task: Docker@2
        displayName: save
        inputs:
          repository: $(ImageName)
          command: save
          arguments: --output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName):$(Build.BuildId)
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'k8s'
          Contents: '*.yaml'
          TargetFolder: '$(build.artifactstagingdirectory)'
      - task: PublishBuildArtifacts@1
        displayName: Publish artifact
        condition: succeededOrFailed()
      - task: ArchiveFiles@2
        displayName: Archive files
        enabled: False
        inputs:
          rootFolderOrFile: $(Build.Repository.Name).exe
...
